name: containers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  containers:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: pocdocker
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Create environment variables file
        run: |
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          envsubst < .env.tpl > .env
      - name: build images
        run: make containers-build

      - name: start service
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: make containers-start

      - name: health check
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: make containers-wait SERVICE=pocdocker

      - name: stop services
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: make containers-stop

      # TODO:
      # - name: docker publish
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   run: ...
